---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "privatebin.fullname" . }}-configs
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "privatebin.name" . }}
    helm.sh/chart: {{ include "privatebin.chart" . }}
data:
{{- range $key, $value := .Values.configs }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
{{- if gt ( .Values.tpls | keys | len ) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "privatebin.fullname" . }}-tpls
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "privatebin.name" . }}
    helm.sh/chart: {{ include "privatebin.chart" . }}
data:
{{- range $key, $value := .Values.tpls }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
{{- end }}
