---
{{- $controller := default "Deployment" .Values.controller.kind -}}
{{- if or (eq $controller "StatefulSet") (eq $controller "Both") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "privatebin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "privatebin.name" . }}
    helm.sh/chart: {{ include "privatebin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "privatebin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.controller.serviceName }}
  serviceName: {{ .Values.controller.serviceName | quote }}   
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "privatebin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "privatebin.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configs
              mountPath: /srv/cfg
            - name: storage
              mountPath: {{ .Values.datapath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "privatebin.fullname" . }}-configs
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteMany" ]
      {{- if .Values.controller.pvc.storageClass }}
        {{- if (eq "-" .Values.controller.pvc.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.controller.pvc.storageClass }}"
        {{- end }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.controller.pvc.requests }}
        volumeMode: Filesystem
{{- end }}
